import '../../sass/common.scss';
import '../../sass/fonts.scss';
import '../../blocks/header/header';
import '../../components/logo/logo';
import '../../components/main-nav/main-nav';
import '../../components/contact/contact';
import '../../components/burger/burger';
import '../../blocks/contrary/contrary';
import '../../components/button/button';
